/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Capa_Interfaz;

import Capa_Logica.AnimacionPnl;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import java.awt.Toolkit;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
    * @author Usuario & Mao
    */
   public class Frm_Principal extends javax.swing.JFrame {

       /**
        * Creates new form Frm_Principal
        */
       private final Color transparente = new Color(0,0,0, 0); // Utilizamos esta combinacion para poner un fondo transparente
       private final Color seleccionado = new Color(17, 114, 255, 50); // Color que tendra un boton al momento de ser seleciconado
       AnimacionPnl anima = new AnimacionPnl();
       private int mouseX, mouseY; // Corrupcion entre cambios de resolucion

       public Frm_Principal() {
           initComponents();
           setBackground(new Color(0.1f, 0.1f, 0.1f, 0.1f)); // Corrupcion entre cambios de resolucion
           setSize(1195, 685); //1080, 642

//           jButton1.setBackground(transparente);
//           jButton1.setForeground(Color.WHITE);
           jButton14.setBackground(transparente);
           jButton13.setBackground(transparente);
           jButton17.setBackground(new Color(0,0,0));
           
          panelRound3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouseX = evt.getX();
                mouseY = evt.getY();
            }
        });

        panelRound3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                // Mover la ventana
                int x = evt.getXOnScreen() - mouseX;
                int y = evt.getYOnScreen() - mouseY;
                setLocation(x, y);
            }
        });


//           
           
   //        jPanel1.setBorder( new FlatLineBorder( new Insets( 50, 50, 50, 0 ), Color.BLACK, 0, 10 ) );
           

       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound3 = new Capa_Interfaz.PanelRound();
        jButton15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panelRound4 = new Capa_Interfaz.PanelRound();
        panelRound5 = new Capa_Interfaz.PanelRound();
        jButton14 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        Pnl_Administrador = new javax.swing.JPanel();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        panelRound1 = new Capa_Interfaz.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(0, 0, 0));
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("x");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        panelRound3.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 40, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new FlatSVGIcon("Imagenes/3PatitosSA.svg"));
        panelRound3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        jButton2.setText("Ser admin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelRound3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 170, 30));

        jButton1.setText("Dejar admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelRound3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 170, 30));

        getContentPane().add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 51));

        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound5.setBackground(new java.awt.Color(0, 0, 0));
        panelRound5.setRoundBottomLeft(20);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setIcon(new FlatSVGIcon("Imagenes/Button.svg"));
        jButton14.setFocusPainted(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        panelRound5.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 50));

        jButton17.setForeground(new java.awt.Color(0, 0, 0));
        jButton17.setIcon(new FlatSVGIcon("Imagenes/Btn_CerrarSesion.svg"));
        jButton17.setFocusPainted(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        panelRound5.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 240, 50));

        jButton18.setIcon(new FlatSVGIcon("Imagenes/Btn_PartesDeEquipo.svg"));
        jButton18.setFocusPainted(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        panelRound5.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 240, 50));

        jButton19.setIcon(new FlatSVGIcon("Imagenes/Btn_Combustibles.svg"));
        jButton19.setFocusPainted(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        panelRound5.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 50));

        jButton20.setIcon(new FlatSVGIcon("Imagenes/Btn_Tanques.svg"));
        jButton20.setFocusPainted(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        panelRound5.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 50));

        jButton21.setIcon(new FlatSVGIcon("Imagenes/Btn_Dispensadores.svg"));
        jButton21.setFocusPainted(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        panelRound5.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 50));

        jButton22.setIcon(new FlatSVGIcon("Imagenes/Btn_Mantenimiento.svg"));
        jButton22.setFocusPainted(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        panelRound5.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 50));

        Pnl_Administrador.setBackground(new java.awt.Color(0, 0, 0));
        Pnl_Administrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton23.setIcon(new FlatSVGIcon("Imagenes/Btn_Vehiculos.svg"));
        jButton23.setFocusPainted(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        Pnl_Administrador.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 50));

        jButton24.setIcon(new FlatSVGIcon("Imagenes/Btn_Usuarios.svg"));
        jButton24.setFocusPainted(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        Pnl_Administrador.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 50));

        panelRound5.add(Pnl_Administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 240));

        panelRound4.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 620));

        jButton13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton13.setIcon(new FlatSVGIcon("Imagenes/Expand2.svg"));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        panelRound4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 30, 30));

        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound4.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 930, 620));

        getContentPane().add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1180, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        
        
        
        anima.animarPanel(panelRound5, jButton13, panelRound1);
        
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged

    }//GEN-LAST:event_formWindowStateChanged

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
         //        try {
            Frm_Login login = null;
            try {
                login = new Frm_Login();
            } catch (URISyntaxException ex) {
                Logger.getLogger(Frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            setVisible(false);
            repaint();
            revalidate();
            //        } catch (SQLException ex) {
            //            Logger.getLogger(JF_Principal.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pnl_Administrador.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pnl_Administrador.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frm_Principal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_Administrador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JLabel jLabel1;
    private Capa_Interfaz.PanelRound panelRound1;
    private Capa_Interfaz.PanelRound panelRound3;
    private Capa_Interfaz.PanelRound panelRound4;
    private Capa_Interfaz.PanelRound panelRound5;
    // End of variables declaration//GEN-END:variables
}
