/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Capa_Interfaz;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Mao
 */
public class Frm_Login extends javax.swing.JFrame {

    Frm_Principal prc;
    
    public Frm_Login() {
        this.prc = new Frm_Principal();
        initComponents();
        setSize(1080, 677);
        setResizable(false);
    }

/**
     * Creates new form Frm_Login
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Interfaz.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelRound4 = new Interfaz.PanelRound();
        txt_Usr = new javax.swing.JTextField();
        panelRound3 = new Interfaz.PanelRound();
        txt_Pwd = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        btn_Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(15, 15, 19));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login to your account");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 250, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        panelRound4.setBackground(new java.awt.Color(235, 235, 235));
        panelRound4.setForeground(new java.awt.Color(215, 215, 215));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Usr.setBackground(new java.awt.Color(235, 235, 235));
        txt_Usr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Usr.setForeground(new java.awt.Color(153, 153, 153));
        txt_Usr.setBorder(null);
        txt_Usr.setOpaque(true);
        txt_Usr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_UsrKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_UsrKeyTyped(evt);
            }
        });
        panelRound4.add(txt_Usr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 20));

        panelRound1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 390, 40));

        panelRound3.setBackground(new java.awt.Color(235, 235, 235));
        panelRound3.setForeground(new java.awt.Color(215, 215, 215));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Pwd.setBackground(new java.awt.Color(235, 235, 235));
        txt_Pwd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Pwd.setForeground(new java.awt.Color(102, 102, 102));
        txt_Pwd.setBorder(null);
        txt_Pwd.setOpaque(true);
        txt_Pwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PwdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PwdKeyTyped(evt);
            }
        });
        panelRound3.add(txt_Pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 20));

        panelRound1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 390, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        btn_Login.setBackground(new java.awt.Color(0, 51, 255));
        btn_Login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Login.setForeground(new java.awt.Color(255, 255, 255));
        btn_Login.setText("Login now");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        panelRound1.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 390, 50));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 530, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pipa.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));



        panelRound1.setBackground(new Color(15, 15, 19, 200));
        panelRound3.setBackground(new Color(15, 15, 19, 200));
        panelRound4.setBackground(new Color(15, 15, 19, 200));
        txt_Pwd.setBackground(new Color(15, 15, 19, 200));
        txt_Usr.setBackground(new Color(15, 15, 19, 200));
        btn_Login.setBackground(new Color(0,51,255, 200));
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UsrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UsrKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_Pwd.requestFocus();
        }
    }//GEN-LAST:event_txt_UsrKeyPressed

    private void txt_UsrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UsrKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetterOrDigit(c) && c != ' ' || txt_Usr.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_UsrKeyTyped

    private void txt_PwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PwdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_Login.doClick();
            txt_Usr.requestFocus();
        }
    }//GEN-LAST:event_txt_PwdKeyPressed

    private void txt_PwdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PwdKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetterOrDigit(c) && c != ' ' || new String(txt_Pwd.getPassword()).length() >= 20) { // Numero de telefono max de 8 digitos
            evt.consume();
        }
    }//GEN-LAST:event_txt_PwdKeyTyped

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
//        String username = txt_Usr.getText();
//        String password = new String(txt_Pwd.getPassword());
//        boolean loginCorrecto = Login.IniciarSesion(username, password);
//        if (loginCorrecto) {
            prc.setLocationRelativeTo(null);
            prc.setVisible(true); // Mostramos el siguiente Frame si el Login fue correcto
            setVisible(false);     // Y ocultamos la ventana actual
//        } else {
//            JOptionPane.showMessageDialog(null, "Ingrese las credenciales correctamente.", "ERROR", JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_btn_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private Interfaz.PanelRound panelRound1;
    private Interfaz.PanelRound panelRound3;
    private Interfaz.PanelRound panelRound4;
    private javax.swing.JPasswordField txt_Pwd;
    private javax.swing.JTextField txt_Usr;
    // End of variables declaration//GEN-END:variables
}
