/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Capa_Interfaz;

import Capa_Logica.Login;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Insets;
import java.awt.event.KeyEvent;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mao
 */
public class Frm_Login extends javax.swing.JFrame {

    Frm_Principal prc;
    Login login = new Login();

    public Frm_Login() throws URISyntaxException {
        this.prc = new Frm_Principal();
        initComponents();
        setSize(1080, 677);
        setResizable(false);
        jPanel1.setOpaque(false);
        jPanel2.setOpaque(false);
        jPanel3.setOpaque(false);
        txt_Usr.setOpaque(false);
        txt_Pwd.setOpaque(false);
        jPanel1.setBackground(new Color(239, 239, 239));
        jPanel2.setBackground(new Color(239, 239, 239));
        jPanel3.setBackground(new Color(239, 239, 239));
        jPanel1.putClientProperty(FlatClientProperties.STYLE, "arc: 50");
        jPanel2.putClientProperty(FlatClientProperties.STYLE, "arc: 20");
        jPanel3.putClientProperty(FlatClientProperties.STYLE, "arc: 20");
        jPanel1.setBorder(new FlatLineBorder(new Insets(16, 16, 16, 16), Color.BLACK, 1, 50));
        jPanel2.setBorder(new FlatLineBorder(new Insets(16, 16, 16, 16), Color.BLACK, 1, 10));
        jPanel3.setBorder(new FlatLineBorder(new Insets(16, 16, 16, 16), Color.BLACK, 1, 10));

    }

    /**
     * Creates new form Frm_Login
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_Login = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_Usr = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txt_Pwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 239, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Login to your account");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 250, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Username");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        btn_Login.setBackground(new java.awt.Color(0, 0, 0));
        btn_Login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Login.setForeground(new java.awt.Color(255, 255, 255));
        btn_Login.setText("Login now");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 390, 50));

        jPanel2.setBackground(new java.awt.Color(215, 215, 215));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Usr.setBackground(new java.awt.Color(239, 239, 239));
        txt_Usr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Usr.setForeground(new java.awt.Color(51, 51, 51));
        txt_Usr.setBorder(null);
        txt_Usr.setOpaque(true);
        txt_Usr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsrActionPerformed(evt);
            }
        });
        txt_Usr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_UsrKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_UsrKeyTyped(evt);
            }
        });
        jPanel2.add(txt_Usr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 390, 40));

        jPanel3.setBackground(new java.awt.Color(215, 215, 215));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Pwd.setBackground(new java.awt.Color(239, 239, 239));
        txt_Pwd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Pwd.setForeground(new java.awt.Color(51, 51, 51));
        txt_Pwd.setBorder(null);
        txt_Pwd.setOpaque(true);
        txt_Pwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PwdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PwdKeyTyped(evt);
            }
        });
        jPanel3.add(txt_Pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 390, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 540, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UsrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UsrKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_Pwd.requestFocus();
        }
    }//GEN-LAST:event_txt_UsrKeyPressed

    private void txt_UsrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UsrKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetterOrDigit(c) && c != ' ' || txt_Usr.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_UsrKeyTyped

    private void txt_PwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PwdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_Login.doClick();
            txt_Usr.requestFocus();
        }
    }//GEN-LAST:event_txt_PwdKeyPressed

    private void txt_PwdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PwdKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetterOrDigit(c) && c != ' ' || new String(txt_Pwd.getPassword()).length() >= 20) { // Numero de telefono max de 8 digitos
            evt.consume();
        }
    }//GEN-LAST:event_txt_PwdKeyTyped

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        try {
            String username = txt_Usr.getText();
            String password = new String(txt_Pwd.getPassword());
            boolean loginCorrecto = login.ValidarLogin(username, password);

            if (loginCorrecto) {
                prc.setLocationRelativeTo(null);
                prc.setVisible(true); // Mostramos el siguiente Frame
                prc.revalidate();
                prc.repaint();
                setVisible(false);  // Ocultamos la ventana actual
            } else {
                JOptionPane.showMessageDialog(null, "Contraseña incorrecta.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese las credenciales correctamente.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void txt_UsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frm_Login().setVisible(true);
                } catch (URISyntaxException ex) {
                    Logger.getLogger(Frm_Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txt_Pwd;
    private javax.swing.JTextField txt_Usr;
    // End of variables declaration//GEN-END:variables
}
