/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Capa_Interfaz;

import Capa_Logica.AnimacionPnl;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;

/**
 *
 * @author Usuario & Mao
 */
public class Frm_Principal extends javax.swing.JFrame { 

    /**
     * Creates new form Frm_Principal
     */
    private final Color transparente = new Color(0, 0, 0, 0);
    private final Color seleccionado = new Color(17, 114, 255, 50);
    private final AnimacionPnl anima = new AnimacionPnl();
    private int mouseX, mouseY; // Corrupcion entre cambios de resolucion

    public Frm_Principal(int rolLogin) {
        initComponents();
        setSize(1195, 685); //1080, 642
        setResizable(false);
        setBackground(new Color(0.1f, 0.1f, 0.1f, 0.1f)); // Corrupcion entre cambios de resolucion
        Listeners();
        if (rolLogin != 1) {
            Pnl_Administrador.setVisible(false);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_BarraDeTitulo = new Capa_Interfaz.PanelRound();
        Btn_Cerrar = new javax.swing.JButton();
        Lbl_IIIPatitos = new javax.swing.JLabel();
        Pnl_AreaDeTrabajo = new Capa_Interfaz.PanelRound();
        Pnl_Menu = new Capa_Interfaz.PanelRound();
        Btn_Dashboard = new javax.swing.JButton();
        Btn_CerrarSesion = new javax.swing.JButton();
        Btn_PartesDeEquipo = new javax.swing.JButton();
        Btn_Combustibles = new javax.swing.JButton();
        Btn_Tanques = new javax.swing.JButton();
        Btn_Dispensadores = new javax.swing.JButton();
        Btn_Mantenimiento = new javax.swing.JButton();
        Pnl_Administrador = new javax.swing.JPanel();
        Btn_Vehiculos = new javax.swing.JButton();
        Btn_Usuarios = new javax.swing.JButton();
        Btn_ExpandirMenu = new javax.swing.JButton();
        Pnl_Contenedor = new Capa_Interfaz.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_BarraDeTitulo.setBackground(new java.awt.Color(0, 0, 0));
        Pnl_BarraDeTitulo.setRoundTopLeft(20);
        Pnl_BarraDeTitulo.setRoundTopRight(20);
        Pnl_BarraDeTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Cerrar.setBackground(new java.awt.Color(0, 0, 0));
        Btn_Cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Cerrar.setText("x");
        Btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CerrarActionPerformed(evt);
            }
        });
        Pnl_BarraDeTitulo.add(Btn_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 40, 50));

        Lbl_IIIPatitos.setBackground(new java.awt.Color(0, 51, 51));
        Lbl_IIIPatitos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Lbl_IIIPatitos.setForeground(new java.awt.Color(204, 204, 204));
        Lbl_IIIPatitos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_IIIPatitos.setIcon(new FlatSVGIcon("Imagenes/Logo.svg"));
        Pnl_BarraDeTitulo.add(Lbl_IIIPatitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 50));

        getContentPane().add(Pnl_BarraDeTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 51));

        Pnl_AreaDeTrabajo.setRoundBottomLeft(20);
        Pnl_AreaDeTrabajo.setRoundBottomRight(20);
        Pnl_AreaDeTrabajo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Menu.setBackground(new java.awt.Color(0, 0, 0));
        Pnl_Menu.setRoundBottomLeft(20);
        Pnl_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Dashboard.setIcon(new FlatSVGIcon("Imagenes/Button.svg"));
        Btn_Dashboard.setFocusPainted(false);
        Btn_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DashboardActionPerformed(evt);
            }
        });
        Pnl_Menu.add(Btn_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 50));

        Btn_CerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        Btn_CerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        Btn_CerrarSesion.setIcon(new FlatSVGIcon("Imagenes/Btn_CerrarSesion.svg"));
        Btn_CerrarSesion.setFocusPainted(false);
        Btn_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CerrarSesionActionPerformed(evt);
            }
        });
        Pnl_Menu.add(Btn_CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 240, 50));

        Btn_PartesDeEquipo.setIcon(new FlatSVGIcon("Imagenes/Btn_PartesDeEquipo.svg"));
        Btn_PartesDeEquipo.setFocusPainted(false);
        Btn_PartesDeEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PartesDeEquipoActionPerformed(evt);
            }
        });
        Pnl_Menu.add(Btn_PartesDeEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 240, 50));

        Btn_Combustibles.setIcon(new FlatSVGIcon("Imagenes/Btn_Combustibles.svg"));
        Btn_Combustibles.setFocusPainted(false);
        Btn_Combustibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CombustiblesActionPerformed(evt);
            }
        });
        Pnl_Menu.add(Btn_Combustibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 50));

        Btn_Tanques.setIcon(new FlatSVGIcon("Imagenes/Btn_Tanques.svg"));
        Btn_Tanques.setFocusPainted(false);
        Btn_Tanques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TanquesActionPerformed(evt);
            }
        });
        Pnl_Menu.add(Btn_Tanques, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 50));

        Btn_Dispensadores.setIcon(new FlatSVGIcon("Imagenes/Btn_Dispensadores.svg"));
        Btn_Dispensadores.setFocusPainted(false);
        Pnl_Menu.add(Btn_Dispensadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 50));

        Btn_Mantenimiento.setIcon(new FlatSVGIcon("Imagenes/Btn_Mantenimiento.svg"));
        Btn_Mantenimiento.setFocusPainted(false);
        Btn_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MantenimientoActionPerformed(evt);
            }
        });
        Pnl_Menu.add(Btn_Mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 50));

        Pnl_Administrador.setBackground(new java.awt.Color(0, 0, 0));
        Pnl_Administrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Vehiculos.setIcon(new FlatSVGIcon("Imagenes/Btn_Vehiculos.svg"));
        Btn_Vehiculos.setFocusPainted(false);
        Btn_Vehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VehiculosActionPerformed(evt);
            }
        });
        Pnl_Administrador.add(Btn_Vehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 50));

        Btn_Usuarios.setIcon(new FlatSVGIcon("Imagenes/Btn_Usuarios.svg"));
        Btn_Usuarios.setFocusPainted(false);
        Btn_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UsuariosActionPerformed(evt);
            }
        });
        Pnl_Administrador.add(Btn_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 50));

        Pnl_Menu.add(Pnl_Administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 240));

        Pnl_AreaDeTrabajo.add(Pnl_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 620));

        Btn_ExpandirMenu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Btn_ExpandirMenu.setIcon(new FlatSVGIcon("Imagenes/Expand2.svg"));
        Btn_ExpandirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ExpandirMenuActionPerformed(evt);
            }
        });
        Pnl_AreaDeTrabajo.add(Btn_ExpandirMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 30, 30));

        Pnl_Contenedor.setLayout(new java.awt.BorderLayout());
        Pnl_AreaDeTrabajo.add(Pnl_Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 940, 620));

        getContentPane().add(Pnl_AreaDeTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1180, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Metodos listeners que permiten el desplazamiento de la ventana mediante el cursor
    private void Listeners() {
        Pnl_BarraDeTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouseX = evt.getX();
                mouseY = evt.getY();
            }
        });

        Pnl_BarraDeTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                // Mover la ventana
                int x = evt.getXOnScreen() - mouseX;
                int y = evt.getYOnScreen() - mouseY;
                setLocation(x, y);
            }
        });
    }

    // Metodo que expande o encoge el panel del menu y el contenedor
    private void Btn_ExpandirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ExpandirMenuActionPerformed
        anima.animarPanel(Pnl_Menu, Btn_ExpandirMenu, Pnl_Contenedor);
    }//GEN-LAST:event_Btn_ExpandirMenuActionPerformed

    // Metodo para salir del programa
    private void Btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Btn_CerrarActionPerformed

    // Metodo para cerrar sesion
    private void Btn_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CerrarSesionActionPerformed
        Frm_Login login = new Frm_Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Btn_CerrarSesionActionPerformed

    private void Btn_VehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VehiculosActionPerformed
        Pnl_Vehiculos Comp = new Pnl_Vehiculos();
//        Comp.setSize(930, 620);
        Comp.setLocation(0, 0);

        Pnl_Contenedor.removeAll();
        Pnl_Contenedor.add(Comp);
        Pnl_Contenedor.revalidate();
        Pnl_Contenedor.repaint();
    }//GEN-LAST:event_Btn_VehiculosActionPerformed

    private void Btn_PartesDeEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PartesDeEquipoActionPerformed
        Pnl_Equipo Comp = new Pnl_Equipo();
        Comp.setSize(930, 620);
        Comp.setLocation(0, 0);
        
        Pnl_Contenedor.removeAll();
        Pnl_Contenedor.add(Comp);
        Pnl_Contenedor.revalidate();
        Pnl_Contenedor.repaint();
    }//GEN-LAST:event_Btn_PartesDeEquipoActionPerformed

    private void Btn_CombustiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CombustiblesActionPerformed
        Pnl_Combustibles Comp = new Pnl_Combustibles();
        Comp.setSize(930, 620);
        Comp.setLocation(0, 0);

        Pnl_Contenedor.removeAll();
        Pnl_Contenedor.add(Comp);
        Pnl_Contenedor.revalidate();
        Pnl_Contenedor.repaint();
    }//GEN-LAST:event_Btn_CombustiblesActionPerformed

    private void Btn_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MantenimientoActionPerformed
        Pnl_Mantenimiento Comp = new Pnl_Mantenimiento();
        Pnl_Contenedor.removeAll();
        Pnl_Contenedor.add(Comp);
        Pnl_Contenedor.revalidate(); 
        Pnl_Contenedor.repaint(); 
    }//GEN-LAST:event_Btn_MantenimientoActionPerformed

    private void Btn_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UsuariosActionPerformed
        Pnl_Usuarios Comp = new Pnl_Usuarios();
        Pnl_Contenedor.removeAll();
        Pnl_Contenedor.add(Comp);
        Pnl_Contenedor.revalidate(); 
        Pnl_Contenedor.repaint(); 
    }//GEN-LAST:event_Btn_UsuariosActionPerformed

    private void Btn_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DashboardActionPerformed
        Pnl_Dashboard Comp = new Pnl_Dashboard();
        Pnl_Contenedor.removeAll();
        Pnl_Contenedor.add(Comp);
        Pnl_Contenedor.revalidate(); 
        Pnl_Contenedor.repaint(); 
    }//GEN-LAST:event_Btn_DashboardActionPerformed

    private void Btn_TanquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TanquesActionPerformed
        Pnl_Tanque Comp = new Pnl_Tanque();
        Pnl_Contenedor.removeAll();
        Pnl_Contenedor.add(Comp);
        Pnl_Contenedor.revalidate();
        Pnl_Contenedor.repaint();
    }//GEN-LAST:event_Btn_TanquesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Principal(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cerrar;
    private javax.swing.JButton Btn_CerrarSesion;
    private javax.swing.JButton Btn_Combustibles;
    private javax.swing.JButton Btn_Dashboard;
    private javax.swing.JButton Btn_Dispensadores;
    private javax.swing.JButton Btn_ExpandirMenu;
    private javax.swing.JButton Btn_Mantenimiento;
    private javax.swing.JButton Btn_PartesDeEquipo;
    private javax.swing.JButton Btn_Tanques;
    private javax.swing.JButton Btn_Usuarios;
    private javax.swing.JButton Btn_Vehiculos;
    private javax.swing.JLabel Lbl_IIIPatitos;
    private javax.swing.JPanel Pnl_Administrador;
    private Capa_Interfaz.PanelRound Pnl_AreaDeTrabajo;
    private Capa_Interfaz.PanelRound Pnl_BarraDeTitulo;
    private Capa_Interfaz.PanelRound Pnl_Contenedor;
    private Capa_Interfaz.PanelRound Pnl_Menu;
    // End of variables declaration//GEN-END:variables
}
