/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Interfaz;

import Capa_Logica.Combustible;
import Capa_Logica.Otros;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Usuario
 */
public class Pnl_Combustibles extends javax.swing.JPanel {

    private final Combustible combustible = new Combustible();
    public int id_actual = 1;
    private String tablaCombustible; 

    /**
     * Creates new form Pnl_VehiculosForm
     */
    public Pnl_Combustibles() {
        this.tablaCombustible = combustible.tablaCombustible;
        initComponents();
        Llenar_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Cmb_Actividad = new javax.swing.JComboBox<>();
        Btn_Nuevo = new javax.swing.JButton();
        Btn_Guardar = new javax.swing.JButton();
        Btn_Modificar = new javax.swing.JButton();
        Txt_Nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Combustibles = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(930, 620));
        setPreferredSize(new java.awt.Dimension(930, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Listas de la");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Table de información, selecciona la linea que necesites:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 420, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 320, 30));

        Cmb_Actividad.setBackground(new java.awt.Color(204, 204, 204));
        Cmb_Actividad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cmb_Actividad.setForeground(new java.awt.Color(102, 102, 102));
        Cmb_Actividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo" }));
        Cmb_Actividad.setBackground(Otros.transparente);
        Cmb_Actividad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(Cmb_Actividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 313, 320, 40));

        Btn_Nuevo.setBackground(new java.awt.Color(51, 51, 51));
        Btn_Nuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Nuevo.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Nuevo.setText("Nuevo Registro");
        Btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NuevoActionPerformed(evt);
            }
        });
        add(Btn_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 310, 30));

        Btn_Guardar.setBackground(new java.awt.Color(51, 51, 51));
        Btn_Guardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Guardar.setText("Guardar Contenido");
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });
        add(Btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 310, 30));

        Btn_Modificar.setBackground(new java.awt.Color(51, 51, 51));
        Btn_Modificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Modificar.setText("Modificar Contenido");
        Btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModificarActionPerformed(evt);
            }
        });
        add(Btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 310, 30));

        Txt_Nombre.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Txt_Nombre.setForeground(new java.awt.Color(102, 102, 102));
        Txt_Nombre.setBackground(Otros.transparente);
        Txt_Nombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_NombreKeyPressed(evt);
            }
        });
        add(Txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 118, 320, 70));

        Tbl_Combustibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_Combustibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_CombustiblesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Combustibles);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 430, 490));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Base de Datos");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 350, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Formulario de Combustibles");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 350, 40));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 430, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Registra, modifica y elimina combustibles:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));

        jLabel7.setIcon(new FlatSVGIcon("Imagenes/Combustible_NombreCombustible.svg"));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 350, 90));

        jLabel5.setIcon(new FlatSVGIcon("Imagenes/Combustible_EstadoCombustible.svg"));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 350, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_NombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        }
    }//GEN-LAST:event_Txt_NombreKeyPressed

    private void Btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NuevoActionPerformed
        Txt_Nombre.setText("");
        try {
            id_actual = Otros.Sig_Id(tablaCombustible);
        } catch (SQLException ex) {
            Logger.getLogger(Pnl_Combustibles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_NuevoActionPerformed

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed

        String nombre = Txt_Nombre.getText();

        int actividad = Cmb_Actividad.getSelectedIndex();

        try {
            int Res = combustible.Insert_Combustible(nombre, actividad);
            if (Res != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Importante", JOptionPane.INFORMATION_MESSAGE);
                Llenar_Table();
            }
        } catch (SQLException ex) {
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }//GEN-LAST:event_Btn_GuardarActionPerformed

    private void Btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModificarActionPerformed

        String nombre = Txt_Nombre.getText();

        int actividad = Cmb_Actividad.getSelectedIndex();


        try {
            int Res = combustible.Update_Combustible(id_actual, nombre, actividad);
            if (Res != 0) {
                JOptionPane.showMessageDialog(null, "Datos actualizados exitosamente", "Importante", JOptionPane.INFORMATION_MESSAGE);
                Llenar_Table();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Datos NO actualizados", "Importante", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }//GEN-LAST:event_Btn_ModificarActionPerformed

    private void Tbl_CombustiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_CombustiblesMouseClicked
        
        int row = Tbl_Combustibles.getSelectedRow();

        DefaultTableModel Modelo = (DefaultTableModel) Tbl_Combustibles.getModel();

        id_actual = (int) Modelo.getValueAt(row, 0);
        Txt_Nombre.setText((String) Modelo.getValueAt(row, 1));
    }//GEN-LAST:event_Tbl_CombustiblesMouseClicked

    public void Llenar_Table() { // Enviar por parametros (table - tablaSQL) si Combustibles requiere mas paneles
        try {
            ResultSet Res = Otros.Consultar_Tabla(tablaCombustible);
            Tbl_Combustibles.setModel(DbUtils.resultSetToTableModel(Res));
        } catch (SQLException ex) {
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JButton Btn_Modificar;
    private javax.swing.JButton Btn_Nuevo;
    private javax.swing.JComboBox<String> Cmb_Actividad;
    private javax.swing.JTable Tbl_Combustibles;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
