/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Interfaz;

import Capa_Logica.Combustible;
import Capa_Logica.Otros;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Usuario
 */
public class Pnl_Combustibles extends javax.swing.JPanel {

    private final Combustible combustible = new Combustible();
    public int id_actual = 1;
    private String tablaCombustible; 

    /**
     * Creates new form Pnl_VehiculosForm
     */
    public Pnl_Combustibles() {
        this.tablaCombustible = combustible.tablaCombustible;
        initComponents();
        Llenar_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Txt_Precio = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        Cmb_Actividad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Btn_Nuevo = new javax.swing.JButton();
        Btn_Guardar = new javax.swing.JButton();
        Btn_Modificar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Txt_Nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Combustibles = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(930, 620));
        setPreferredSize(new java.awt.Dimension(930, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Sigue el combustible activo/inactivo?");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Actividad:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 80, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 320, 30));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Listas de la");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 350, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Table de información, selecciona la linea que necesites:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, 30));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        Txt_Precio.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Precio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_Precio.setForeground(new java.awt.Color(51, 51, 51));
        Txt_Precio.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Txt_Precio, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Txt_Precio, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 310, 40));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 420, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nombre:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Digita el nombre del combustible");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 320, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Precio:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 80, 40));

        Cmb_Actividad.setBackground(new java.awt.Color(204, 204, 204));
        Cmb_Actividad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cmb_Actividad.setForeground(new java.awt.Color(102, 102, 102));
        Cmb_Actividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo" }));
        Cmb_Actividad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(Cmb_Actividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 310, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Digita el precio del combustible, Ejemplo: 0.00₡ (Con \".\")");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 30));

        Btn_Nuevo.setBackground(new java.awt.Color(51, 51, 51));
        Btn_Nuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Nuevo.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Nuevo.setText("Nuevo Registro");
        Btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NuevoActionPerformed(evt);
            }
        });
        add(Btn_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 310, 30));

        Btn_Guardar.setBackground(new java.awt.Color(51, 51, 51));
        Btn_Guardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Guardar.setText("Guardar Contenido");
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });
        add(Btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 310, 30));

        Btn_Modificar.setBackground(new java.awt.Color(51, 51, 51));
        Btn_Modificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Modificar.setText("Modificar Contenido");
        Btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModificarActionPerformed(evt);
            }
        });
        add(Btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 310, 30));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        Txt_Nombre.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Txt_Nombre.setForeground(new java.awt.Color(51, 51, 51));
        Txt_Nombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_NombreKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 40));

        Tbl_Combustibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_Combustibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_CombustiblesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Combustibles);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 430, 490));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Base de Datos");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 350, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Formulario de Combustibles");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 350, 40));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 430, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Registra, modifica y elimina combustibles:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_NombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Txt_Precio.requestFocus();
        }
    }//GEN-LAST:event_Txt_NombreKeyPressed

    private void Btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NuevoActionPerformed
        Txt_Nombre.setText("");
        Txt_Precio.setText("");
        try {
            id_actual = Otros.Sig_Id(tablaCombustible);
        } catch (SQLException ex) {
            Logger.getLogger(Pnl_Combustibles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_NuevoActionPerformed

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed

        String nombre = Txt_Nombre.getText();

        String precio = Txt_Precio.getText();

        int actividad = Cmb_Actividad.getSelectedIndex();

        try {
            int Res = combustible.Insert_Combustible(nombre, precio, actividad);
            if (Res != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Importante", JOptionPane.INFORMATION_MESSAGE);
                Llenar_Table();
            }
        } catch (SQLException ex) {
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }//GEN-LAST:event_Btn_GuardarActionPerformed

    private void Btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModificarActionPerformed

        String nombre = Txt_Nombre.getText();

        String precio = Txt_Precio.getText();

        int actividad = Cmb_Actividad.getSelectedIndex();


        try {
            int Res = combustible.Update_Combustible(id_actual, nombre, precio, actividad);
            if (Res != 0) {
                JOptionPane.showMessageDialog(null, "Datos actualizados exitosamente", "Importante", JOptionPane.INFORMATION_MESSAGE);
                Llenar_Table();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Datos NO actualizados", "Importante", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }//GEN-LAST:event_Btn_ModificarActionPerformed

    private void Tbl_CombustiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_CombustiblesMouseClicked
        
        int row = Tbl_Combustibles.getSelectedRow();

        DefaultTableModel Modelo = (DefaultTableModel) Tbl_Combustibles.getModel();

        id_actual = (int) Modelo.getValueAt(row, 0);
        Txt_Nombre.setText((String) Modelo.getValueAt(row, 1));
        Txt_Precio.setText(String.valueOf(Modelo.getValueAt(row, 2)));
    }//GEN-LAST:event_Tbl_CombustiblesMouseClicked

    public void Llenar_Table() { // Enviar por parametros (table - tablaSQL) si Combustibles requiere mas paneles
        try {
            ResultSet Res = Otros.Consultar_Tabla(tablaCombustible);
            Tbl_Combustibles.setModel(DbUtils.resultSetToTableModel(Res));
        } catch (SQLException ex) {
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JButton Btn_Modificar;
    private javax.swing.JButton Btn_Nuevo;
    private javax.swing.JComboBox<String> Cmb_Actividad;
    private javax.swing.JTable Tbl_Combustibles;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JTextField Txt_Precio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
