/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Interfaz;

import Capa_Logica.Otros;
import Capa_Logica.Usuario;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Insets;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mao
 */
public class Pnl_Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_Usuarios
     */
    private final Usuario usuario = new Usuario();
    private int id_actual = 1;
    private int rolActual = 1;
    private int actividadActual = 1;
    private final Color transparente = new Color(0, 0, 0, 0);

    public Pnl_Usuarios() {
        initComponents();
        Llenar_Table();
        Txt_Nombre.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Combustibles = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Cmb_Actividad = new javax.swing.JComboBox<>();
        Cmb_Actividad1 = new javax.swing.JComboBox<>();
        Txt_Nombre = new javax.swing.JTextField();
        Txt_Precio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 320, 30));

        Tbl_Combustibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Combustibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_CombustiblesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Combustibles);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 430, 300));

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 120, 40));

        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 120, 40));

        Cmb_Actividad.setBackground(new java.awt.Color(204, 204, 204));
        Cmb_Actividad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cmb_Actividad.setForeground(new java.awt.Color(102, 102, 102));
        Cmb_Actividad.setBackground(Otros.transparente);
        Cmb_Actividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Administrador" }));
        Cmb_Actividad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(Cmb_Actividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 333, 320, 40));
        Cmb_Actividad.setBackground(Otros.transparente);
        Cmb_Actividad.putClientProperty("JComboBox.isTableCellEditor", Boolean.TRUE);

        Cmb_Actividad1.setBackground(new java.awt.Color(204, 204, 204));
        Cmb_Actividad1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cmb_Actividad1.setForeground(new java.awt.Color(102, 102, 102));
        Cmb_Actividad1.setBackground(Otros.transparente);
        Cmb_Actividad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo" }));
        Cmb_Actividad1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(Cmb_Actividad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 443, 320, 40));

        Txt_Nombre.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Txt_Nombre.setForeground(new java.awt.Color(102, 102, 102));
        Txt_Nombre.setText("Nombre de Usuario");
        Txt_Nombre.setBackground(Otros.transparente);
        Txt_Nombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_NombreKeyPressed(evt);
            }
        });
        add(Txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 320, 70));

        Txt_Precio.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Precio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Txt_Precio.setForeground(new java.awt.Color(102, 102, 102));
        Txt_Precio.setBackground(Otros.transparente);
        Txt_Precio.setText("Contraseña");
        Txt_Precio.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        add(Txt_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 320, 70));

        jLabel9.setIcon(new FlatSVGIcon("Imagenes/TextArea.svg"));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 350, 90));

        jLabel1.setIcon(new FlatSVGIcon("Imagenes/Usuarios_Contrasena.svg"));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 350, 90));

        jLabel4.setIcon(new FlatSVGIcon("Imagenes/Usuarios_Estado.svg"));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 350, 90));

        jLabel5.setIcon(new FlatSVGIcon("Imagenes/Usuarios_Rol.svg"));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 350, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_NombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Txt_Precio.requestFocus();
        }
    }//GEN-LAST:event_Txt_NombreKeyPressed

    private void Tbl_CombustiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_CombustiblesMouseClicked

        int row = Tbl_Combustibles.getSelectedRow();

        DefaultTableModel Modelo = (DefaultTableModel) Tbl_Combustibles.getModel();

        id_actual = Integer.parseInt(Modelo.getValueAt(row, 0).toString());
        Txt_Nombre.setText(String.valueOf(Modelo.getValueAt(row, 1)));
        Txt_Precio.setText("1");
        Cmb_Actividad.setSelectedIndex(Integer.parseInt(Modelo.getValueAt(row, 2).toString()));
        Cmb_Actividad1.setSelectedIndex(Integer.parseInt(Modelo.getValueAt(row, 3).toString()));
        rolActual = Integer.parseInt(Modelo.getValueAt(row, 2).toString());
        actividadActual = Integer.parseInt(Modelo.getValueAt(row, 3).toString());
    }//GEN-LAST:event_Tbl_CombustiblesMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nombre = Txt_Nombre.getText();
        String precio = Otros.EncriptarMD5(Txt_Precio.getText().strip());
        int rol = Cmb_Actividad.getSelectedIndex();
        int actividad = Cmb_Actividad1.getSelectedIndex();
        System.out.println(precio);

        try {
            int Res = usuario.Insert_Usuario(nombre, precio, rol, actividad);
            if (Res != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Importante", JOptionPane.INFORMATION_MESSAGE);
                Llenar_Table();
            }
        } catch (SQLException ex) {
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String nombre = Txt_Nombre.getText();
            String precio = Otros.EncriptarMD5(Txt_Precio.getText().strip());
            int rolNuevo = Cmb_Actividad.getSelectedIndex();
            int actividadNueva = Cmb_Actividad1.getSelectedIndex();

            if (rolActual == 1 && actividadActual == 1) {
                if (rolNuevo == 0 && usuario.Consultar_CantAdmins() == 1) {
                    JOptionPane.showMessageDialog(null, "Debe existir al menos un administrador.", "Info", JOptionPane.INFORMATION_MESSAGE);
                    return;
                } else if (actividadNueva == 0 && usuario.Consultar_CantAdmins() == 1) {
                    JOptionPane.showMessageDialog(null, "Debe existir al menos un administrador activo", "Info", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }

            int resultado = usuario.Update_Usuario(id_actual, nombre, precio, rolNuevo, actividadNueva);
            if (resultado != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados correctamente.", "Info", JOptionPane.INFORMATION_MESSAGE);
                Llenar_Table();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.toString());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    public void Llenar_Table() {
        try {
            ResultSet Res = usuario.Consultar_TablaUsuario();
            Tbl_Combustibles.setModel(DbUtils.resultSetToTableModel(Res));
        } catch (SQLException ex) {
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cmb_Actividad;
    private javax.swing.JComboBox<String> Cmb_Actividad1;
    private javax.swing.JTable Tbl_Combustibles;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JTextField Txt_Precio;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
