/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Interfaz;

import java.awt.event.KeyEvent;
import Capa_Logica.*;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Elias
 */
public class Pnl_Vehiculos extends javax.swing.JPanel {

    String tabla = "vehiculos";
    public int id_actual = 1;
    private final Combustible combustible = new Combustible();
    private final Otros Sql = new Otros();
    private final Vehiculos vehiculos = new Vehiculos();

    /**
     * Creates new form Pnl_Vehiculos
     */
    public Pnl_Vehiculos() {
        initComponents();
        Llenar_Table_Combustibles();
        Llenar_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTabla = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Btn_Guardar = new javax.swing.JButton();
        Btn_Modificar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Txt_Placa = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        Cmb_Activo = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        Btn_Nuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Combustibles = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        Txt_Descripcion = new javax.swing.JTextField();
        Txt_Marca = new javax.swing.JTextField();
        Txt_Modelo = new javax.swing.JTextField();
        Lbl_Id = new javax.swing.JLabel();
        Lbl_Combustible = new javax.swing.JLabel();
        labelpro = new javax.swing.JLabel();
        labelpro1 = new javax.swing.JLabel();
        labelpro2 = new javax.swing.JLabel();
        labelpro3 = new javax.swing.JLabel();
        labelpro4 = new javax.swing.JLabel();
        labelpro6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tbl_Vehiculos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(930, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelTabla.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setMinimumSize(new java.awt.Dimension(930, 620));
        jPanel1.setPreferredSize(new java.awt.Dimension(930, 620));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 880, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Placa:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Digite la placa del vehiculo en el espacio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 30));

        Btn_Guardar.setBackground(new java.awt.Color(51, 51, 51));
        Btn_Guardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Guardar.setIcon(new FlatSVGIcon("Imagenes/GuardarContenido.svg"));
        Btn_Guardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Btn_Guardar.setBackground(Otros.transparente);
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 330, 35));

        Btn_Modificar.setBackground(new java.awt.Color(51, 51, 51));
        Btn_Modificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Modificar.setIcon(new FlatSVGIcon("Imagenes/ModificarContenido.svg"));
        Btn_Modificar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Btn_Modificar.setBackground(Otros.transparente);
        Btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 330, 35));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Formulario de Vehiculos");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 350, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Registra, modifica y elimina combustibles:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));

        Txt_Placa.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Placa.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Txt_Placa.setForeground(new java.awt.Color(0, 0, 255));
        Txt_Placa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Txt_Placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_PlacaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Txt_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Txt_Placa, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 70));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 430, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 430, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 430, 30));

        Cmb_Activo.setBackground(new java.awt.Color(204, 204, 204));
        Cmb_Activo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cmb_Activo.setForeground(new java.awt.Color(102, 102, 102));
        Cmb_Activo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo" }));
        Cmb_Activo.setBackground(Otros.transparente);
        Cmb_Activo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(Cmb_Activo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 363, 320, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 430, 10));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Seleccione la linea del combustible del vehiculo, (solo de un sutil click)");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, 30));

        Btn_Nuevo.setBackground(new java.awt.Color(51, 51, 51));
        Btn_Nuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Nuevo.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Nuevo.setIcon(new FlatSVGIcon("Imagenes/NuevoRegistro.svg"));
        Btn_Nuevo.setBackground(Otros.transparente);
        Btn_Nuevo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NuevoActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 330, 35));

        Tbl_Combustibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_Combustibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_CombustiblesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Combustibles);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 300, 160));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Combustible:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 110, 40));

        Txt_Descripcion.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Descripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Txt_Descripcion.setForeground(new java.awt.Color(102, 102, 102));
        Txt_Descripcion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Txt_Descripcion.setBackground(Otros.transparente);
        Txt_Descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_DescripcionKeyPressed(evt);
            }
        });
        jPanel1.add(Txt_Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 320, 50));

        Txt_Marca.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Marca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Txt_Marca.setForeground(new java.awt.Color(102, 102, 102));
        Txt_Marca.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Txt_Marca.setBackground(Otros.transparente);
        Txt_Marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_MarcaKeyPressed(evt);
            }
        });
        jPanel1.add(Txt_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 320, 50));

        Txt_Modelo.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Modelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Txt_Modelo.setForeground(new java.awt.Color(102, 102, 102));
        Txt_Modelo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Txt_Modelo.setBackground(Otros.transparente);
        jPanel1.add(Txt_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 320, 50));

        Lbl_Id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Lbl_Id.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(Lbl_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 100, 30));

        Lbl_Combustible.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Lbl_Combustible.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(Lbl_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 100, 30));

        labelpro.setIcon(new FlatSVGIcon("Imagenes/Vehiculo_Id.svg"));
        jPanel1.add(labelpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 140, 80));

        labelpro1.setIcon(new FlatSVGIcon("Imagenes/Vehiculo_Nombre.svg"));
        jPanel1.add(labelpro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 350, 90));

        labelpro2.setIcon(new FlatSVGIcon("Imagenes/Vehiculo_Marca.svg"));
        jPanel1.add(labelpro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 350, 90));

        labelpro3.setIcon(new FlatSVGIcon("Imagenes/Vehiculo_Modelo.svg"));
        jPanel1.add(labelpro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 350, 90));

        labelpro4.setIcon(new FlatSVGIcon("Imagenes/Vehiculo_Estado.svg"));
        jPanel1.add(labelpro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 350, 90));

        labelpro6.setIcon(new FlatSVGIcon("Imagenes/Vehiculo_Combustible.svg"));
        jPanel1.add(labelpro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 140, 80));

        PanelTabla.addTab("Formulario", jPanel1);

        jPanel9.setBackground(new java.awt.Color(246, 246, 246));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tbl_Vehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_Vehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_VehiculosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tbl_Vehiculos);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 870, 420));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Listas de la");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Base de Datos");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Table de información, selecciona la linea que necesites, regresa al panel anterior para modificarla:");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));
        jPanel9.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 890, 10));
        jPanel9.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 890, 10));

        PanelTabla.addTab("Tabla", jPanel9);

        add(PanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1, 910, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed

        String placa = Txt_Placa.getText();
        String descripcion = Txt_Descripcion.getText();
        String marca = Txt_Marca.getText();
        String modelo = Txt_Modelo.getText();
        int id_combustible = Integer.parseInt(Lbl_Id.getText());
        int actividad = Cmb_Activo.getSelectedIndex();

        try {
            int Res = vehiculos.Insert_Vehiculo(placa, descripcion, marca, modelo, id_combustible, actividad);
            if (Res != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Importante", JOptionPane.INFORMATION_MESSAGE);
                Llenar_Table();
            }
        } catch (SQLException ex) {
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }//GEN-LAST:event_Btn_GuardarActionPerformed

    private void Btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModificarActionPerformed

        String placa = Txt_Placa.getText();
        String descripcion = Txt_Descripcion.getText();
        String marca = Txt_Marca.getText();
        String modelo = Txt_Modelo.getText();
        int id_combustible = Integer.parseInt(Lbl_Id.getText());
        int actividad = Cmb_Activo.getSelectedIndex();

        try {
            int Res = vehiculos.Update_Vehiculo(id_actual, placa, descripcion, marca, modelo, id_combustible, actividad);
            if (Res != 0) {
                JOptionPane.showMessageDialog(null, "Datos actualizados exitosamente", "Importante", JOptionPane.INFORMATION_MESSAGE);
                Llenar_Table();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Datos NO actualizados", "Importante", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }//GEN-LAST:event_Btn_ModificarActionPerformed

    private void Txt_PlacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_PlacaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            labelpro.requestFocus();
        }
    }//GEN-LAST:event_Txt_PlacaKeyPressed

    private void Btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NuevoActionPerformed
        Txt_Descripcion.setText("");
        Txt_Marca.setText("");
        Txt_Modelo.setText("");
        Txt_Placa.setText("");
        Lbl_Combustible.setText("");
        Lbl_Id.setText("");
        try {
            id_actual = Sql.Sig_Id(tabla);
        } catch (SQLException ex) {
            Logger.getLogger(Pnl_Combustibles.class.getName()).log(Level.SEVERE, null, ex);
        }
        Llenar_Table();
    }//GEN-LAST:event_Btn_NuevoActionPerformed

    private void Tbl_CombustiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_CombustiblesMouseClicked
        int row = Tbl_Combustibles.getSelectedRow();
        String actividad = "inactivo";

        DefaultTableModel Modelo = (DefaultTableModel) Tbl_Combustibles.getModel();
        actividad = String.valueOf(Modelo.getValueAt(row, 2));

        if (actividad.equals("activo")) {
            Lbl_Id.setText(String.valueOf(Modelo.getValueAt(row, 0)));
            Lbl_Combustible.setText(String.valueOf(Modelo.getValueAt(row, 1)));
        } else {
            JOptionPane.showMessageDialog(null, "Combustible no disponible actualmente, espera a que esté disponible o activo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Tbl_CombustiblesMouseClicked

    private void Txt_MarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_MarcaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Txt_Modelo.requestFocus();
        }
    }//GEN-LAST:event_Txt_MarcaKeyPressed

    private void Tbl_VehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_VehiculosMouseClicked
        int row = Tbl_Vehiculos.getSelectedRow();
        DefaultTableModel Modelo = (DefaultTableModel) Tbl_Vehiculos.getModel();

        id_actual = Integer.parseInt(Modelo.getValueAt(row, 0).toString());
        Txt_Placa.setText(String.valueOf(Modelo.getValueAt(row, 1)));
        Txt_Descripcion.setText(String.valueOf(Modelo.getValueAt(row, 2)));
        Txt_Marca.setText(String.valueOf(Modelo.getValueAt(row, 3)));
        Txt_Modelo.setText(String.valueOf(Modelo.getValueAt(row, 4)));
        Lbl_Id.setText(String.valueOf(Modelo.getValueAt(row, 5)));
        Lbl_Combustible.setText("");
        
    }//GEN-LAST:event_Tbl_VehiculosMouseClicked

    private void Txt_DescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_DescripcionKeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            Txt_Precio.requestFocus();
            //        }
    }//GEN-LAST:event_Txt_DescripcionKeyPressed

    public void Llenar_Table_Combustibles() {
        try {
            ResultSet Res = combustible.Consultar_Combustible();
            Tbl_Combustibles.setModel(DbUtils.resultSetToTableModel(Res));
        } catch (SQLException ex) {
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }

    public void Llenar_Table() {
        try {
            ResultSet Res = Otros.Consultar_Tabla(tabla);
            Tbl_Vehiculos.setModel(DbUtils.resultSetToTableModel(Res));
        } catch (SQLException ex) {
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JButton Btn_Modificar;
    private javax.swing.JButton Btn_Nuevo;
    private javax.swing.JComboBox<String> Cmb_Activo;
    private javax.swing.JLabel Lbl_Combustible;
    private javax.swing.JLabel Lbl_Id;
    private javax.swing.JTabbedPane PanelTabla;
    private javax.swing.JTable Tbl_Combustibles;
    private javax.swing.JTable Tbl_Vehiculos;
    private javax.swing.JTextField Txt_Descripcion;
    private javax.swing.JTextField Txt_Marca;
    private javax.swing.JTextField Txt_Modelo;
    private javax.swing.JTextField Txt_Placa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel labelpro;
    private javax.swing.JLabel labelpro1;
    private javax.swing.JLabel labelpro2;
    private javax.swing.JLabel labelpro3;
    private javax.swing.JLabel labelpro4;
    private javax.swing.JLabel labelpro6;
    // End of variables declaration//GEN-END:variables
}
