/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Interfaz;

import Capa_Logica.Mantenimiento;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Insets;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Mao
 */
public class Pnl_Mantenimiento extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_Mantenimiento
     */
    private final Mantenimiento asignaMantenimiento = new Mantenimiento();

    public Pnl_Mantenimiento() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelRound1 = new Capa_Interfaz.PanelRound();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(204, 204, 204));
        panelRound1.setBackground(new java.awt.Color(0,0,0,0));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setText("jTextField1");
        panelRound1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 50));
        jTextField2.setBorder(new FlatLineBorder(new Insets(16, 16, 16, 16), Color.BLACK, 2, 30));

        jTextField3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setText("jTextField1");
        panelRound1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 170, 50));
        jTextField3.setBorder(new FlatLineBorder(new Insets(16, 16, 16, 16), Color.BLACK, 2, 30));

        jCalendar1.setSundayForeground(new java.awt.Color(204, 0, 0));
        jCalendar1.setTodayButtonText("");
        jCalendar1.setWeekdayForeground(new java.awt.Color(0, 102, 255));
        panelRound1.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 330, 240));

        jTextField4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 51, 51));
        jTextField4.setText("jTextField1");
        panelRound1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, 50));
        jTextField4.setBorder(new FlatLineBorder(new Insets(16, 16, 16, 16), Color.BLACK, 2, 30));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText(" Código Usuario:");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 170, 40));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" Código Vehículo:");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" Código Mantenimiento:");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 250, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Crear marco para esta vaina ");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 300, 60));

        jButton1.setText("Borrar");
        panelRound1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 100, 40));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelRound1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 100, 40));

        jButton3.setText("Modificar");
        panelRound1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 100, 40));

        jTabbedPane1.addTab("tab1", panelRound1);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 910, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int id_vehiculo = Integer.parseInt(jTextField2.getText().strip());
            int id_mantenimiento = Integer.parseInt(jTextField4.getText().strip());
            int id_usuario = Integer.parseInt(jTextField3.getText().strip());
            Date fechaSeleccionada = jCalendar1.getDate();
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            String fechaFormateada = formato.format(fechaSeleccionada);

            int resultado = asignaMantenimiento.Insert_AsignaMantenimiento(id_vehiculo, id_mantenimiento, fechaFormateada, id_usuario);
            if (resultado != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados correctamente.", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private Capa_Interfaz.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
