/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Interfaz;

import Capa_Logica.Equipo;
import Capa_Logica.Otros;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Insets;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mao
 */
public class Pnl_Equipo extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_Equipo
     */
    private final Equipo equipo = new Equipo();
    private int id_actual = 1;
    private Otros otros = new Otros();
    private String tablaEquipo;

    public Pnl_Equipo() {
        this.tablaEquipo = equipo.tablaTipos;
        initComponents();
        Llenar_Tabla();
        Listeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_Combustibles = new javax.swing.JTable();
        Txt_Nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Cmb_Actividad1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(246, 246, 246));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setIcon(new FlatSVGIcon("Imagenes/GuardarContenido.svg"));
        jButton4.setBackground(Otros.transparente);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 330, 35));

        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.setIcon(new FlatSVGIcon("Imagenes/ModificarContenido.svg"));
        jButton5.setBackground(Otros.transparente);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 330, 35));

        Tbl_Combustibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_Combustibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_CombustiblesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tbl_Combustibles);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 430, 340));

        Txt_Nombre.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Txt_Nombre.setForeground(new java.awt.Color(102, 102, 102));
        Txt_Nombre.setBackground(Otros.transparente);
        Txt_Nombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_NombreKeyPressed(evt);
            }
        });
        jPanel3.add(Txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 320, 70));

        jLabel9.setIcon(new FlatSVGIcon("Imagenes/ParteEquipo_Nombre.svg"));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 350, 90));

        Cmb_Actividad1.setBackground(new java.awt.Color(204, 204, 204));
        Cmb_Actividad1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cmb_Actividad1.setForeground(new java.awt.Color(102, 102, 102));
        Cmb_Actividad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo" }));
        Cmb_Actividad1.setBackground(Otros.transparente);
        Cmb_Actividad1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(Cmb_Actividad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 213, 320, 40));

        jLabel5.setIcon(new FlatSVGIcon("Imagenes/ParteEquipo_Estado.svg"));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 350, 90));

        jRadioButton1.setIcon(new FlatSVGIcon("Imagenes/Filtro_MostrarTodos.svg"));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setSelectedIcon(new FlatSVGIcon("Imagenes/Filtro_MostrarTodosSelected.svg"));
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 70, -1));

        jRadioButton2.setIcon(new FlatSVGIcon("Imagenes/Filtro_MostrarActivos.svg"));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelectedIcon(new FlatSVGIcon("Imagenes/Filtro_MostrarActivosSelected.svg"));
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 80, -1));

        jRadioButton3.setIcon(new FlatSVGIcon("Imagenes/Filtro_MostrarInactivos.svg"));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setSelectedIcon(new FlatSVGIcon("Imagenes/Filtro_MostrarInactivosSelected.svg"));
        jPanel3.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 90, -1));

        jButton1.setToolTipText("");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setIcon(new FlatSVGIcon("Imagenes/NuevoRegistro.svg"));
        jButton1.setBackground(Otros.transparente);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 330, 35));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 940, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void Listeners() {
        ActionListener listener = (ActionEvent e) -> {
            if (jRadioButton1.isSelected()) {
                Llenar_TablaFiltro(Otros.filtroTodos);
            } else if (jRadioButton2.isSelected()) {
                Llenar_TablaFiltro(Otros.filtroActivos);
            } else if (jRadioButton3.isSelected()) {
                Llenar_TablaFiltro(Otros.filtroInactivos);
            }
        };
        jRadioButton1.addActionListener(listener);
        jRadioButton2.addActionListener(listener);
        jRadioButton3.addActionListener(listener);
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String descripcion = Txt_Nombre.getText().strip();
            int actividad = Cmb_Actividad1.getSelectedIndex();

            int resultado = equipo.Insert_Equipo(descripcion, actividad);
            if (resultado != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados correctamente.", "Info", JOptionPane.INFORMATION_MESSAGE);
                Llenar_Tabla();
                jRadioButton1.setSelected(true);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.toString());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            int actividad = Cmb_Actividad1.getSelectedIndex();
            int id = id_actual;
            String descripcion = Txt_Nombre.getText().strip();

            int resultado = equipo.Update_Equipo(id, descripcion, actividad);
            if (resultado != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados correctamente.", "Info", JOptionPane.INFORMATION_MESSAGE);
                Llenar_Tabla();
                jRadioButton1.setSelected(true);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.toString());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Tbl_CombustiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_CombustiblesMouseClicked
        //        try {
        //            id_actual = Sql.Sig_Id(tabla);
        //        } catch (SQLException ex) {
        //            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        //        }

        int row = Tbl_Combustibles.getSelectedRow();

        DefaultTableModel Modelo = (DefaultTableModel) Tbl_Combustibles.getModel();

        id_actual = (int) Modelo.getValueAt(row, 0);
        Txt_Nombre.setText((String) Modelo.getValueAt(row, 1));
    }//GEN-LAST:event_Tbl_CombustiblesMouseClicked

    private void Txt_NombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreKeyPressed
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            Txt_Precio.requestFocus();
//        }
    }//GEN-LAST:event_Txt_NombreKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Txt_Nombre.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    public void Llenar_Tabla() {
        try {
            ResultSet Res = Otros.Consultar_Tabla(tablaEquipo);
            Tbl_Combustibles.setModel(DbUtils.resultSetToTableModel(Res));
        } catch (SQLException ex) {
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }
    
    public void Llenar_TablaFiltro(String filtro) {
        try {
            ResultSet Res = Otros.Consultar_TablaFiltro(tablaEquipo, filtro);
            Tbl_Combustibles.setModel(DbUtils.resultSetToTableModel(Res));
        } catch (SQLException ex) {
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cmb_Actividad1;
    private javax.swing.JTable Tbl_Combustibles;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
