/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Interfaz;

import Capa_Logica.Equipo;
import Capa_Logica.Otros;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Insets;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mao
 */
public class Pnl_Equipo extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_Equipo
     */
    private final Equipo equipo = new Equipo();
    private int id_actual = 1;
    private Otros otros = new Otros();
    private String tablaEquipo; 
    
    public Pnl_Equipo() {
        this.tablaEquipo = equipo.tablaTipos;
        initComponents();
        Llenar_Tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_Combustibles = new javax.swing.JTable();
        Txt_Nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Cmb_Actividad1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 120, 40));

        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 120, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Falta poner filtros");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 380, 40));

        Tbl_Combustibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_Combustibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_CombustiblesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tbl_Combustibles);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 430, 340));

        Txt_Nombre.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Txt_Nombre.setForeground(new java.awt.Color(102, 102, 102));
        Txt_Nombre.setText("Nombre de la parte del equipo");
        Txt_Nombre.setBackground(Otros.transparente);
        Txt_Nombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_NombreKeyPressed(evt);
            }
        });
        jPanel3.add(Txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 320, 70));

        jLabel9.setIcon(new FlatSVGIcon("Imagenes/ParteEquipo_Nombre.svg"));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 350, 90));

        Cmb_Actividad1.setBackground(new java.awt.Color(204, 204, 204));
        Cmb_Actividad1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cmb_Actividad1.setForeground(new java.awt.Color(102, 102, 102));
        Cmb_Actividad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo" }));
        Cmb_Actividad1.setBackground(Otros.transparente);
        Cmb_Actividad1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(Cmb_Actividad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 203, 320, 40));

        jLabel4.setIcon(new FlatSVGIcon("Imagenes/ParteEquipo_Estado.svg"));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 350, 90));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String descripcion = Txt_Nombre.getText().strip();
            int actividad = Cmb_Actividad1.getSelectedIndex();

            int resultado = equipo.Insert_Equipo(descripcion, actividad);
            if (resultado != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados correctamente.", "Info", JOptionPane.INFORMATION_MESSAGE);
                Llenar_Tabla();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.toString());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            int actividad = Cmb_Actividad1.getSelectedIndex();
            int id = id_actual;
            String descripcion = Txt_Nombre.getText().strip();

            int resultado = equipo.Update_Equipo(id, descripcion, actividad);
            if (resultado != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados correctamente.", "Info", JOptionPane.INFORMATION_MESSAGE);
                Llenar_Tabla();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.toString());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Tbl_CombustiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_CombustiblesMouseClicked
        //        try {
            //            id_actual = Sql.Sig_Id(tabla);
            //        } catch (SQLException ex) {
            //            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
            //        }

        int row = Tbl_Combustibles.getSelectedRow();

        DefaultTableModel Modelo = (DefaultTableModel) Tbl_Combustibles.getModel();

        id_actual = (int) Modelo.getValueAt(row, 0);
        Txt_Nombre.setText((String) Modelo.getValueAt(row, 1));
    }//GEN-LAST:event_Tbl_CombustiblesMouseClicked

    private void Txt_NombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreKeyPressed
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            Txt_Precio.requestFocus();
//        }
    }//GEN-LAST:event_Txt_NombreKeyPressed

    
    public void Llenar_Tabla() {
        try {
            ResultSet Res = Otros.Consultar_Tabla(tablaEquipo);
            Tbl_Combustibles.setModel(DbUtils.resultSetToTableModel(Res));
        } catch (SQLException ex) {
            System.out.println("\u001B[31mERROR:\u001B[0m " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cmb_Actividad1;
    private javax.swing.JTable Tbl_Combustibles;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
